Update AvatarEditorService.yaml
Roblox/creator-docs pull request #385
Opened 2024-01-18 00:13 UTC by brcohen59

## Changes
We're adding a new return value in the table of GetOutfitDetails for ModerationStatus enum
with the following PR. Once we flip the flag in that PR, we will hope to merge in this change to the doc

https://github.rbx.com/GameEngine/game-engine/pull/67814

## Checks

By submitting your pull request for review, you agree to the following:

- [x] This contribution was created in whole or in part by me, and I have the right to submit it under the terms of this repository's open source licenses.
- [x] I understand and agree that this contribution and a record of it are public, maintained indefinitely, and may be redistributed under the terms of this repository's open source licenses.
- [x] To the best of my knowledge, all proposed changes are accurate.

2024-02-06 00:44 UTC, brcohen59 commented
Spoke with Brent about merging this in since he's OOO to give approval on git so I can turn on the related flag that enables this

2024-02-06 22:33 UTC, IgnisRBX approved these changes

2024-02-10 19:13 UTC, ArdiYusif reviewed
Salam

2024-02-11 17:58 UTC, shencia requested changes
__put different types of buildings

2024-02-14 23:58 UTC, merged