Small info about AccessoryDescription and BodyPartDescription
Roblox/creator-docs pull request #424
Opened 2024-02-15 21:15 UTC by karl-police

## Changes

Adds a description for https://create.roblox.com/docs/en-us/reference/engine/classes/AccessoryDescription and https://create.roblox.com/docs/en-us/reference/engine/classes/BodyPartDescription with a little bit of consistency from how it's written in ``HumanoidDescription``. I didn't add much because I am not really familiar with the syntax, nor is it finished, but the sort of idea is already there, so 🤷 

## Checks

By submitting your pull request for review, you agree to the following:

- [x] This contribution was created in whole or in part by me, and I have the right to submit it under the terms of this repository's open source licenses.
- [x] I understand and agree that this contribution and a record of it are public, maintained indefinitely, and may be redistributed under the terms of this repository's open source licenses.
- [x] To the best of my knowledge, all proposed changes are accurate.

2024-02-17 08:01 UTC, totallytavi requested changes
I've left comments for stuff that flagged the GitHub Actions bot

2024-02-17 08:01 UTC, totallytavi commented on content/en-us/reference/engine/classes/AccessoryDescription.yaml
> +  Describes the appearance of an Accessory for the HumanoidDescription.'
Remove the `'` at the end of this line

2024-02-17 08:01 UTC, totallytavi commented on content/en-us/reference/engine/classes/BodyPartDescription.yaml
> +  **BodyPartDescription** is an object that stores the description for an Avatar's Body Parts, such as the Color. It is ment to be placed underneath a `Class.HumanoidDescription`, in order to work wi
Typo: replace `ment` with `meant`

2024-02-17 08:01 UTC, totallytavi commented on content/en-us/reference/engine/classes/AccessoryDescription.yaml
> +  **AccessoryDescription** is an object that stores the description for an `Class.Accessory`. It is ment to be placed underneath a `Class.HumanoidDescription`, in order to work with `Class.Humanoid:A
Typo: replace `ment` with `meant`

2024-02-17 08:01 UTC, totallytavi commented on content/en-us/reference/engine/classes/BodyPartDescription.yaml
> +  Describes the appearance of a Body Part for the HumanoidDescription'
Remove the `'` at the end of this line

2024-02-19 23:41 UTC, totallytavi approved these changes
LGTM

2024-02-20 01:21 UTC, Jozhuaheine123457 commented
Oh okay

2024-02-20 01:31 UTC, Jozhuaheine123457 requested changes
This need two change as long then u well be good

2024-02-20 14:20 UTC, karl-police commented
uhhh?

2024-02-20 18:13 UTC, IgnisRBX commented on content/en-us/reference/engine/classes/BodyPartDescription.yaml
> +  Describes the appearance of a Body Part for the HumanoidDescription
```suggestion
  Describes the appearance of a `Enum. BodyPart` for the `Class.HumanoidDescription`.
```

2024-02-20 18:15 UTC, IgnisRBX commented on content/en-us/reference/engine/classes/BodyPartDescription.yaml
> +  **BodyPartDescription** is an object that stores the description for an Avatar's Body Parts, such as the Color. It is meant to be placed underneath a `Class.HumanoidDescription`, in order to work w
```suggestion
  **BodyPartDescription** is an object that stores the description for an avatar's body parts, such as the `Class.BodyPartDescription.Color|Color`. It is meant to be placed underneath a `Class.HumanoidDescription` in order to work with `Class.Humanoid:ApplyDescription()`.
```

2024-02-20 18:17 UTC, IgnisRBX commented on content/en-us/reference/engine/classes/AccessoryDescription.yaml
> +  Describes the appearance of an Accessory for the HumanoidDescription.
```suggestion
  Describes the appearance of an `Class.Accessory` for the `Class.HumanoidDescription`.
```

2024-02-20 18:17 UTC, IgnisRBX commented on content/en-us/reference/engine/classes/AccessoryDescription.yaml
> +  **AccessoryDescription** is an object that stores the description for an `Class.Accessory`. It is meant to be placed underneath a `Class.HumanoidDescription`, in order to work with `Class.Humanoid:
```suggestion
  **AccessoryDescription** is an object that stores the description for an `Class.Accessory`. It is meant to be placed underneath a `Class.HumanoidDescription` in order to work with `Class.Humanoid:ApplyDescription()`.
```

2024-02-20 19:29 UTC, IgnisRBX approved these changes

2024-02-20 20:03 UTC, IgnisRBX commented
Thanks for the contribution! I made a few tiny edits and linked up to other API pages.

2024-02-20 20:03 UTC, merged