Update create-the-map.md
Roblox/creator-docs pull request #801
Opened 2024-09-01 20:23 UTC by Summerscreations

**ye##** Changes

## Checks

By submitting your pull request for review, you agree to the following:

- [ ] This contribution was created in whole or in part by me, and I have the right to submit it under the terms of this repository's open source licenses.
- [ ] I understand and agree that this contribution and a record of it are public, maintained indefinitely, and may be redistributed under the terms of this repository's open source licenses.
- [ ] To the best of my knowledge, all proposed changes are accurate.

2024-09-01 20:24 UTC, Summerscreations commented
Amazing

2024-09-02 01:55 UTC, totallytavi requested changes
This doesn't improve the documentation. If you're looking to test things, consider using your fork that you made and just keep it there.

2024-09-02 01:55 UTC, totallytavi requested changes

2024-09-02 01:55 UTC, totallytavi commented on content/en-us/education/adventure-game-series/create-the-map.md
> +---hello
This seems like a test thing.

2024-09-03 15:59 UTC, closed without merging